name: CI

on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Sanity Check
        run: echo "CI is functioning!"
