name: CI Tests

on: 
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v5

            -   name: Build Docker
                run: docker build -t textstats . 

            -   name: Run Docker Container tests
                run: docker run textstats python -m pytest 
